#!/bin/bash
# Helper library for the Roadmap Synthesiser agent.
# Source this in scripts/roadmap-synth.sh — do not run directly.
#
# Provides:
#   roadmap_csv_init  <csv_path>      — ensure header exists
#   roadmap_csv_append <csv_path> ... — append one history row
#   roadmap_obsidian_url <path>       — emit obsidian:// URL for a vault file
#   roadmap_age_days <iso_date>       — days since a date string (YYYY-MM-DD)
#   roadmap_parse_synthesis <json>    — parse Claude's JSON → env-var style output

# Initialise the history CSV (idempotent)
roadmap_csv_init() {
  local csv="$1"
  if [ ! -f "$csv" ]; then
    echo "date,total_open,theme_count,epic_count,orphan_count,oldest_orphan_age_days" > "$csv"
  fi
}

# Append one row to the history CSV
# Args: csv  date  total_open  theme_count  epic_count  orphan_count  oldest_orphan_age_days
roadmap_csv_append() {
  local csv="$1" date="$2" total_open="$3" theme_count="$4" \
        epic_count="$5" orphan_count="$6" oldest_age="$7"
  echo "${date},${total_open},${theme_count},${epic_count},${orphan_count},${oldest_age}" >> "$csv"
}

# Return an obsidian:// deep-link URL for an absolute vault path.
# Obsidian uses: obsidian://open?vault=<vault-name>&file=<relative-path>
# We derive the vault name from the parent directory of the .obsidian folder.
# Falls back to a plain file:// URL if we cannot locate the vault root.
roadmap_obsidian_url() {
  local abs_path="$1"
  # Walk upward to find the .obsidian config dir = vault root
  local dir
  dir=$(dirname "$abs_path")
  while [ "$dir" != "/" ] && [ "$dir" != "." ]; do
    if [ -d "$dir/.obsidian" ]; then
      local vault_name relative_path
      vault_name=$(basename "$dir")
      # shellcheck disable=SC2001
      relative_path=$(echo "$abs_path" | sed "s|${dir}/||")
      # URL-encode spaces as %20
      relative_path=$(echo "$relative_path" | sed 's/ /%20/g')
      vault_name=$(echo "$vault_name" | sed 's/ /%20/g')
      echo "obsidian://open?vault=${vault_name}&file=${relative_path}"
      return 0
    fi
    dir=$(dirname "$dir")
  done
  echo "file://${abs_path}"
}

# Return the number of days since a YYYY-MM-DD date string.
# Returns 0 if the date cannot be parsed.
roadmap_age_days() {
  local date_str="$1"
  python3 -c "
from datetime import date, datetime
try:
    d = datetime.strptime('${date_str}', '%Y-%m-%d').date()
    print((date.today() - d).days)
except Exception:
    print(0)
" 2>/dev/null || echo "0"
}

# Parse the Claude synthesis JSON output and emit shell-friendly key=value lines.
# Prints counts to stdout; caller can eval or read them.
# Expected JSON schema (see clustering prompt in roadmap-synth.sh):
#   { themes:[{name,issues:[],description}],
#     epics:[{name,motivation,issues:[],sequence}],
#     orphans:[{id,reason}],
#     risks:[{type,description}] }
roadmap_parse_synthesis() {
  local json_file="$1"
  python3 - "$json_file" << 'PYEOF'
import json, sys

path = sys.argv[1]
try:
    with open(path) as f:
        raw = f.read().strip()
    # Claude sometimes wraps JSON in markdown fences
    if raw.startswith("```"):
        raw = "\n".join(
            line for line in raw.splitlines()
            if not line.strip().startswith("```")
        )
    data = json.loads(raw)
    themes  = data.get("themes",  [])
    epics   = data.get("epics",   [])
    orphans = data.get("orphans", [])
    risks   = data.get("risks",   [])
    print(f"THEME_COUNT={len(themes)}")
    print(f"EPIC_COUNT={len(epics)}")
    print(f"ORPHAN_COUNT={len(orphans)}")
    print(f"RISK_COUNT={len(risks)}")
except Exception as e:
    print(f"THEME_COUNT=0", flush=True)
    print(f"EPIC_COUNT=0",  flush=True)
    print(f"ORPHAN_COUNT=0",flush=True)
    print(f"RISK_COUNT=0",  flush=True)
    print(f"PARSE_ERROR={e}", file=__import__('sys').stderr)
PYEOF
}

# Render the full Markdown roadmap doc from Claude's synthesis JSON.
# Args: json_file  as_of_date  project_name
# Prints Markdown to stdout.
roadmap_render_markdown() {
  local json_file="$1" as_of="$2" project="${3:-Lift}"
  python3 - "$json_file" "$as_of" "$project" << 'PYEOF'
import json, sys, textwrap

path, as_of, project = sys.argv[1], sys.argv[2], sys.argv[3]

try:
    with open(path) as f:
        raw = f.read().strip()
    if raw.startswith("```"):
        raw = "\n".join(
            l for l in raw.splitlines()
            if not l.strip().startswith("```")
        )
    data = json.loads(raw)
except Exception as e:
    print(f"# {project} Roadmap — parse error\n\n{e}")
    sys.exit(1)

themes  = data.get("themes",  [])
epics   = data.get("epics",   [])
orphans = data.get("orphans", [])
risks   = data.get("risks",   [])

lines = []
lines.append(f"# {project} Roadmap")
lines.append(f"")
lines.append(f"> As of {as_of}. Generated by Roadmap Synthesiser.")
lines.append(f"")

# ── Themes ──────────────────────────────────────────────────────────────────
lines.append(f"## Themes ({len(themes)})")
lines.append("")
if themes:
    for i, t in enumerate(themes, 1):
        name  = t.get("name", "Unnamed")
        desc  = t.get("description", "")
        issues = t.get("issues", [])
        issue_str = ", ".join(str(x) for x in issues) if issues else "—"
        lines.append(f"### {i}. {name}")
        if desc:
            lines.append(f"{desc}")
        lines.append(f"")
        lines.append(f"**Issues:** {issue_str}")
        lines.append("")
else:
    lines.append("_No themes identified._")
    lines.append("")

# ── Epics ────────────────────────────────────────────────────────────────────
lines.append(f"## Proposed Epics ({len(epics)})")
lines.append("")
if epics:
    for i, e in enumerate(epics, 1):
        name  = e.get("name", "Unnamed Epic")
        motiv = e.get("motivation", "")
        issues = e.get("issues", [])
        seq   = e.get("sequence", "")
        issue_str = ", ".join(str(x) for x in issues) if issues else "—"
        lines.append(f"### Epic {i}: {name}")
        if motiv:
            lines.append(f"**Motivation:** {motiv}")
            lines.append("")
        lines.append(f"**Issues:** {issue_str}")
        if seq:
            lines.append(f"**Sequence:** {seq}")
        lines.append("")
else:
    lines.append("_No epics proposed._")
    lines.append("")

# ── Orphans ──────────────────────────────────────────────────────────────────
lines.append(f"## Orphan Issues ({len(orphans)})")
lines.append("")
lines.append("> These issues are open >30 days with no activity, or don't fit any theme. Review for close/rescope.")
lines.append("")
if orphans:
    for o in orphans:
        oid    = o.get("id", "?")
        reason = o.get("reason", "")
        title  = o.get("title", "")
        age    = o.get("age_days", "")
        age_str = f" ({age}d old)" if age else ""
        lines.append(f"- **{oid}**{age_str} — {title}")
        if reason:
            lines.append(f"  _Reason: {reason}_")
else:
    lines.append("_No orphans identified._")
lines.append("")

# ── Risks ────────────────────────────────────────────────────────────────────
lines.append(f"## Roadmap Risks ({len(risks)})")
lines.append("")
if risks:
    for r in risks:
        rtype = r.get("type", "")
        rdesc = r.get("description", "")
        label = f"**{rtype}:** " if rtype else ""
        lines.append(f"- {label}{rdesc}")
else:
    lines.append("_No risks flagged._")
lines.append("")

# ── Footer ───────────────────────────────────────────────────────────────────
lines.append("---")
lines.append(f"_Updated {as_of} by Roadmap Synthesiser_")

print("\n".join(lines))
PYEOF
}
